# Generated by Django 4.2.11 on 2024-04-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmtask',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llmtask',
            name='search_input',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
