version: '3'

services:
  docs:
    image: django_celery_llm_tasks_local_docs
    container_name: django_celery_llm_tasks_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_celery_llm_tasks:/app/django_celery_llm_tasks:z
    ports:
      - '9000:9000'
    command: /start-docs
